In [1]:
""" Example to demonstrate how to use queues
Author: Chip Huyen
Prepared for the class CS 20SI: "TensorFlow for Deep Learning Research"
cs20si.stanford.edu
"""

' Example to demonstrate how to use queues\nAuthor: Chip Huyen\nPrepared for the class CS 20SI: "TensorFlow for Deep Learning Research"\ncs20si.stanford.edu\n'

In [2]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import numpy as np
import tensorflow as tf

In [3]:
N_SAMPLES = 1000
NUM_THREADS = 4

In [4]:
# np.random.randn() random between 0 and 1
# sigma * np.random.randn(...) + mu
# sigma -> variance
# mu -> mean
2.5 * np.random.randn(2, 4) + 3

array([[ 4.8542593 , -0.01029792,  3.83861219,  0.61781011],
       [ 3.76901031,  6.3132012 ,  2.03939708, -1.89189399]])

In [5]:
# Generating some simple data
# create 1000 random samples, each is a 1D array from the normal distribution (10, 1)
data = 10 * np.random.randn(N_SAMPLES, 4) + 1 

In [6]:
# create 1000 random labels of 0 and 1
target = np.random.randint(0, 2, size=N_SAMPLES) 

In [7]:
queue = tf.FIFOQueue(capacity=50, dtypes=[tf.float32, tf.int32], shapes=[[4], []])

In [8]:
enqueue_op = queue.enqueue_many([data, target])
data_sample, label_sample = queue.dequeue()

In [9]:
# create ops that do something with data_sample and label_sample

In [10]:
# create NUM_THREADS to do enqueue
qr = tf.train.QueueRunner(queue, [enqueue_op] * NUM_THREADS)

In [11]:
with tf.Session() as sess:
	# create a coordinator, launch the queue runner threads.
	coord = tf.train.Coordinator()
	enqueue_threads = qr.create_threads(sess, coord=coord, start=True)
	try:
		for step in range(100): # do to 100 iterations
			if coord.should_stop():
				break
			data_batch, label_batch = sess.run([data_sample, label_sample])
			print(data_batch)
			print(label_batch)
	except Exception as e:
		coord.request_stop(e)
	finally:
		coord.request_stop()
		coord.join(enqueue_threads)

[ -5.23803663  15.65011406 -21.53064537 -15.32979107]
1
[ -2.38965631   4.98938656 -13.95070267   9.27775764]
1
[-1.35273075  4.72424364  2.86820364 -7.2201643 ]
0
[ 16.01215172  10.93052387  -4.03430462  -0.87043196]
1
[ 11.90573597   0.32078815  12.02414608   2.76715708]
1
[-12.57418251  -0.78797656  10.4852438   -4.30044603]
1
[-16.67137718   7.61119175  -4.26706648   6.152668  ]
1
[ 11.25352287   8.3217535   -4.93516588   4.90648603]
1
[  0.1269661    0.83080459   7.47028351  20.0108757 ]
0
[  3.359936     1.15109968   5.24083519  15.35933113]
0
[-9.61187172 -6.0742836   5.60089636  4.65852165]
1
[ 2.06652021 -1.25938964  2.12112164 -1.77210283]
1
[ -2.22307706   2.13243604  -3.0326705   12.12556076]
0
[-10.24617863  -9.16341782 -15.92488575 -13.63031769]
0
[ 14.21244621 -12.91999722   2.81901145   2.06504226]
0
[ -5.21752977  13.56492424  -1.72393537  -8.82034683]
0
[ -9.28061962 -10.09086418 -10.92248344  -3.41602063]
0
[ 1.02541232  1.88361478  5.32584906  5.66913891]
0
[  0.753