In [1]:
import tensorflow as tf
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)
with tf.Session() as sess:
    # add this line to use TensorBoard.
    writer = tf.summary.FileWriter('./graphs', sess.graph)
    print(sess.run(x))
writer.close() # close the writer when you’re done using it

5


In [2]:
import os 
os.system('tensorboard --logdir="./graphs" --port 6006')

0

In [4]:
# Explicitly name them
import tensorflow as tf
a = tf.constant(2, name="a")
b = tf.constant(3, name="b")
x = tf.add(a, b, name="add")
writer = tf.summary.FileWriter("./graphs", sess.graph)
with tf.Session() as sess:
    print(sess.run(x)) # >> 5
writter.close()

5


In [5]:
import os 
os.system('tensorboard --logdir="./graphs" --port 6006')

0

In [8]:
import tensorflow as tf
a = tf.constant([2, 2], name="a")
b = tf.constant([[0, 1], [2, 3]], name="b")
x = tf.add(a, b, name="add")
y = tf.multiply(a, b, name="mul")
with tf.Session() as sess:
    x, y = sess.run([x, y])
print(x) 

[[2 3]
 [4 5]]


In [9]:
print(y)

[[0 2]
 [4 6]]


In [10]:
tf.zeros([2, 3], tf.int32) 

<tf.Tensor 'zeros:0' shape=(2, 3) dtype=int32>

In [12]:
tf.fill([2, 3], 8)

<tf.Tensor 'Fill:0' shape=(2, 3) dtype=int32>

In [13]:
W = tf.Variable(tf.truncated_normal([700, 10]))
with tf.Session() as sess:
    sess.run(W.initializer)
print(W)

<tf.Variable 'Variable:0' shape=(700, 10) dtype=float32_ref>


In [15]:
W = tf.Variable(tf.truncated_normal([700, 10]))
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval())

[[ 0.80801749  1.2444495  -0.84056389 ...,  0.51757753  0.14080909
   0.19970658]
 [ 0.1527465   1.60971344  0.63527966 ...,  0.79318625  0.20549093
  -1.77896118]
 [ 0.74780679 -0.8731342   0.75213057 ...,  0.65796989 -0.73025405
   1.93688977]
 ..., 
 [ 0.49716008  0.23655796 -0.4683845  ...,  0.28347823 -0.46473834
  -1.00329292]
 [ 0.05218363  0.63760448 -1.48955333 ...,  0.87040073 -0.64665604
  -0.73171872]
 [-0.58123612 -1.52656639 -0.74222279 ...,  0.30192488 -1.74024963
  -1.28035998]]


In [20]:
# create a variable whose original value is 2
my_var = tf.Variable(2, name="my_var")

# assign a * 2 to a and call that op a_times_two
my_var_times_two = my_var.assign(2 * my_var)

with tf.Session() as sess:
    sess.run(my_var.initializer)
    sess.run(my_var_times_two) # >> 4
    print(my_var_times_two.eval())
    sess.run(my_var_times_two) # >> 8
    print(my_var_times_two.eval())
    sess.run(my_var_times_two) # >> 16
    print(my_var_times_two.eval())

8
32
128


In [24]:
# Each session maintains it own
W = tf.Variable(10)
sess1 = tf.Session()
sess2 = tf.Session()
sess1.run(W.initializer)
sess2.run(W.initializer)
print(sess1.run(W.assign_add(10)))
print(sess2.run(W.assign_sub(2)))
sess1.close()
sess2.close()

20
8


In [25]:
sess = tf.InteractiveSession()
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b
# We can just use 'c.eval()' without specifying the context 'sess'
print(c.eval())
sess.close()

30.0


In [26]:
# create a placeholder of type float 32-bit, shape is a vector of 3 elements
a = tf.placeholder(tf.float32, shape=[3])
# create a constant of type float 32-bit, shape is a vector of 3 elements
b = tf.constant([5, 5, 5], tf.float32)
# use the placeholder as you would a constant or a variable
c = a + b # Short for tf.add(a, b)

with tf.Session() as sess:
    # feed [1, 2, 3] to placeholder a via the dict {a: [1, 2, 3]}
    # fetch value of c
    print(sess.run(c, {a: [1, 2, 3]})) # the tensor a is the key, not the string ‘a’

[ 6.  7.  8.]


In [33]:
# Normal loading
tf.reset_default_graph()
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')
z = tf.add(x, y) # you create the node for add node before executing the graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    writer = tf.summary.FileWriter('./my_graph/l2', sess.graph)
    for _ in range(10):
        print(sess.run(z))
    writer.close()

30
30
30
30
30
30
30
30
30
30


In [31]:
tf.get_default_graph().as_graph_def()

node {
  name: "x/initial_value"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 10
      }
    }
  }
}
node {
  name: "x"
  op: "VariableV2"
  attr {
    key: "container"
    value {
      s: ""
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
      }
    }
  }
  attr {
    key: "shared_name"
    value {
      s: ""
    }
  }
}
node {
  name: "x/Assign"
  op: "Assign"
  input: "x"
  input: "x/initial_value"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@x"
      }
    }
  }
  attr {
    key: "use_locking"
    value {
      b: true
    }
  }
  attr {
    key: "validate_shape"
    value {
      b: true
    }
  }
}
node {
  name: "x/read"
  op: "Identity"
  input

In [32]:
import os 
os.system('tensorboard --logdir="./my_graph/l2" --port 6006')

0

In [37]:
# Lazy loading
tf.reset_default_graph()
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    writer = tf.summary.FileWriter('./my_graph/l2', sess.graph)
    for _ in range(10):
        print(sess.run(tf.add(x, y))) # someone decides to be clever to save one line of code
    writer.close()

30
30
30
30
30
30
30
30
30
30


In [38]:
tf.get_default_graph().as_graph_def()

node {
  name: "x/initial_value"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 10
      }
    }
  }
}
node {
  name: "x"
  op: "VariableV2"
  attr {
    key: "container"
    value {
      s: ""
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
      }
    }
  }
  attr {
    key: "shared_name"
    value {
      s: ""
    }
  }
}
node {
  name: "x/Assign"
  op: "Assign"
  input: "x"
  input: "x/initial_value"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@x"
      }
    }
  }
  attr {
    key: "use_locking"
    value {
      b: true
    }
  }
  attr {
    key: "validate_shape"
    value {
      b: true
    }
  }
}
node {
  name: "x/read"
  op: "Identity"
  input

In [39]:
import os 
os.system('tensorboard --logdir="./my_graph/l2" --port 6006')

0